## This is test deployment for Kubernetes platforms.
## This is not intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-codiad
  name: test-codiad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-codiad
  template:
    metadata:
      labels:
        app: test-codiad
    spec:
      containers:
      - image: bitnami/codiad
        name: codiad
---
apiVersion: v1
kind: Service
metadata:
  name: test-neo4j
  labels:
    app: test-neo4j
spec:
  ports:
  - name: bolt
    port: 7687
    targetPort: 7687
  - name: http
    port: 7474
    targetPort: 7474
  - name: https
    port: 7473
    targetPort: 7473
  selector:
    app: test-neo4j
  type: ClusterIP
